config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'beaches/populate_beaches_from_google_places', to: 'beaches#populate_beaches_from_google_places'
  get '/beaches/nearby', to: 'beaches#nearby', as: 'nearby_beaches'
  resources :beaches
  root to: "beaches#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beach.rb
class Beach < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/beaches_controller.rb
require 'dotenv/load'
require 'httparty'

class BeachesController < ApplicationController
  before_action :set_beach, only: %i[ show edit update destroy ]

  # GET /beaches
  def index
    search_query = params[:search_query]

    if search_query.present?
      # Search the database for matching beaches
      @beaches = Beach.where("name ILIKE ?", "%#{search_query}%")

      if @beaches.present?
        # Beaches found in the database, show them in the view
        render :index
      else
        # Fetch beaches from the Google Places API
        url = 'https://maps.googleapis.com/maps/api/place/textsearch/json'
        query = {
          query: {
            query: search_query + ' beaches',
            key: ENV['GOOGLE_MAPS_API_KEY']
          }
        }

        # Send the API request
        response = HTTParty.get(url, query)
        results = response.parsed_response['results']

        if results.present?
          # Create new Beach instances and save them to the database
          @beaches = results.map do |result|
            Beach.create(
              name: result['name'],
              address: result['formatted_address'],
              photo_url: result['photos'].first['photo_reference']
            )
          end

          redirect_to beaches_path, notice: 'Beaches populated successfully'
        else
          redirect_to beaches_path, alert: 'No beaches found'
        end
      end
    else
      @beaches = Beach.all
    end
  end


  # GET /beaches/1
  def show
  end

  # GET /beaches/new
  def new
    @beach = Beach.new
  end

  # GET /beaches/1/edit
  def edit
  end

  # POST /beaches
  def create
    @beach = Beach.new(beach_params)

    if @beach.save
      redirect_to @beach, notice: "Beach was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /beaches/1
  def update
    if @beach.update(beach_params)
      redirect_to @beach, notice: "Beach was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /beaches/1
  def destroy
    @beach.destroy
    redirect_to beaches_url, notice: "Beach was successfully destroyed.", status: :see_other
  end

    def nearby
      url = URI("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522%2C151.1957362&radius=1500&type=land&keyword=beach&key=#{ENV['GOOGLE_MAPS_API_KEY']}")

      https = Net::HTTP.new(url.host, url.port)
      https.use_ssl = true

      request = Net::HTTP::Get.new(url)

      response = https.request(request)
      puts response.read_body

      # Process the response and render the view
      # You can assign the response data to an instance variable and use it in your view
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beach
      @beach = Beach.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def beach_params
      params.require(:beach).permit(:address, :latitude, :longitude)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/places_controller.rb
# app/controllers/places_controller.rb

require 'httparty'

class PlacesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beaches/_beach.html.erb
<div id="<%= dom_id beach %>">
  <p>
    <strong>Address:</strong>
    <%= beach.address %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= beach.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= beach.longitude %>
  </p>

</div>

app/views/beaches/_form.html.erb
<%= simple_form_for(@beach) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :address %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/beaches/edit.html.erb
<h1>Editing beach</h1>

<%= render "form", beach: @beach %>

<br>

<div>
  <%= link_to "Show this beach", @beach %> |
  <%= link_to "Back to beaches", beaches_path %>
</div>

app/views/beaches/index.html.erb
  <p style="color: green"><%= notice %></p>


<%# Form to search text in the Google Places API and return the json with name address and photo %>


<%# Display of each Beach instance in a card with a photo and a title and address underneath %>
<% if @beaches.present? %>
  <div class="row row-cols-4">
    <% @beaches.each do |beach| %>
      <div class="col-md-3">
        <div class="card beach-card">
          <% if beach.photo_url.present? %>
            <% photo_reference = beach.photo_url %>
            <% google_maps_api_key = ENV['GOOGLE_MAPS_API_KEY'] %>
            <% image_url = "https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photo_reference=#{photo_reference}&key=#{google_maps_api_key}" %>
            <%= image_tag image_url, class: "card-img-top beach-image" %>
          <% else %>
            <!-- Placeholder image if photo_url is not available -->
            <%= image_tag "broken-beach.jpg", class: "card-img-top beach-image" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title fw-1"><%= beach.name %></h5>
            <hr>
            <p class="card-text"><%= beach.address %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/beaches/nearby.html.erb
<% json_response = JSON.parse(response) %>

<% json_response.each do |place| %>
  <div>
    <h3><%= place['name'] %></h3>
    <p>Address: <%= place['vicinity'] %></p>
    <p>Rating: <%= place['rating'] %></p>
    <p>Latitude: <%= place['geometry']['location']['lat'] %></p>
    <p>Longitude: <%= place['geometry']['location']['lng'] %></p>
    <% if place['photos'].present? %>
      <h4>Photos:</h4>
      <% place['photos'].each do |photo| %>
        <img src="<%= photo['photo_reference'] %>" alt="Place Photo" />
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/beaches/new.html.erb
<h1>New beach</h1>

<%= render "form", beach: @beach %>

<br>

<div>
  <%= link_to "Back to beaches", beaches_path %>
</div>

app/views/beaches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @beach %>

<div>
  <%= link_to "Edit this beach", edit_beach_path(@beach) %> |
  <%= link_to "Back to beaches", beaches_path %>

  <%= button_to "Destroy this beach", @beach, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGeocoding</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script type="module" src="./index.js"></script>
  </head>
  <body>
  <%= render "shared/flashes" %>
  <%= render "shared/navbar" %>
  <!--The div element for the map -->
  <%= yield %>
    <div style="display: none">
    <input
      id="pac-input"
      class="controls"
      type="text"
      placeholder="Enter a location"
    />
  </div>
  <div id="map"></div>

  <div id="infowindow-content">
    <span id="place-name" class="title"></span><br />
    <strong>Place ID:</strong> <span id="place-id"></span><br />
    <span id="place-address"></span>
  </div>

    <!--
      The `defer` attribute causes the callback to execute after the full HTML
      document has been parsed. For non-blocking uses, avoiding race conditions,
      and consistent behavior across browsers, consider loading using Promises.
      See https://developers.google.com/maps/documentation/javascript/load-maps-js-api
      for more information.
      -->
    <% if false %>
    <script
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>
&callback=initMap&libraries=places&v=weekly"
      defer
    ></script>
   <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1>Maps Demo</h1>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%# Form takes query and executes the populate_beaches_from_google_places action
    in beaches controller %>
    <%= form_tag beaches_path, method: :get do %>
      <%= text_field_tag :search_query, params[:search_query], placeholder: "Search for a beach" %>
      <%= submit_tag 'Search' %>
    <% end %>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>